AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "api-gateway template"

Parameters:
  StageName:
    Type: String
    Description: Stage name
    Default: prod
  UserPoolArn:
    Type: String

Resources:
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: "REST API with Cognito Authorizer"
      StageName: !Sub ${StageName}
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Sub UserPoolArn
            Identity:
              Header: Authorization
              ValidationExpression: "^Bearer [-0-9a-zA-Z\\.\\_]*$"
              ReauthorizeEvery: 300
            IdentitySource: method.request.header.Authorization

  # MyCognitoAuthorizer:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Name: CognitoUserPoolAuthorizer
  #     Type: COGNITO_USER_POOLS
  #     ProviderARNs:
  #       - !Ref UserPoolArn # Ensure you export this from your Cognito stack
  #     RestApiId: !Ref AppApi

Outputs:
  AppApiRootUrl:
    Description: "URL for the root of the API Gateway"
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"

  AppApiId:
    Description: "ID for the API Gateway"
    Value: !Ref AppApi
