AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "api-gateway template"

Parameters:
  StageName:
    Type: String
    Description: Stage name
    Default: prod
  UserPoolArn:
    Type: String

Resources:
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: "REST API with Cognito Authorizer"
      StageName: !Sub ${StageName}
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 300

Outputs:
  AppApiRootUrl:
    Description: "URL for the root of the API Gateway"
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"

  AppApiId:
    Description: "ID for the API Gateway"
    Value: !Ref AppApi
