AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure template

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  TableName:
    Type: String
    Description: Name of the DynamoDB table

Resources:
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodb.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName

Outputs:
  CognitoUserPoolArn:
    Value: !GetAtt CognitoStack.Outputs.UserPoolArn

  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolId

  UserPoolClientId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
