service: dental-clinic-managerment-system

frameworkVersion: "3"

custom:
  region: ap-southeast-1
  account-id: "014183400304"
  pythonRequirements:
    slim: true
    strip: true
    dockerizePip: true
    layer: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  timeout: 5s
  memorySize: 256
  architecture: x86_64
  tracing:
    lambda: true

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!yarn.lock"
    - "!package-lock.json"
    - "!package.json"
    - "!**/__pycache__/**"
    - "!tmp/**"
    - "!.github/**"
    - "!README.md"
    - "!.gitignore"
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

functions:
  # Module authentication
  login:
    name: ${sls:stage}-login
    handler: src/authentication/login.handler
    role: ApiAccessRole
    events:
      - http:
          path: login
          method: post
          cors: true
          integration: lambda-proxy
    package:
      exclude:
        - "**"
      include:
        - src/authentication/login.handler

resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-userpool

    ApiAccessRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: nguyen-tran-clinic-ApiAccessRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "ApiAccessPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                    - "cognito-idp:AdminInitiateAuth"
                  Resource:
                    - "*"
