service: dental-clinic-managerment-system

frameworkVersion: "3"

custom:
  region: ap-southeast-1
  account-id: "014183400304"
  userpool-id: "ap-southeast-1_aZafRDpVV"
  pythonRequirements:
    slim: true
    strip: true
    dockerizePip: true
    layer: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  timeout: 5
  memorySize: 256
  architecture: x86_64
  tracing:
    lambda: true
  environment:
    USER_POOL_ID: "ap-southeast-1_VHlxORHB8"
    CLIENT_ID: "294cp2c3br64lmdhbns9466scd"

package:
  individually: true

functions:
  # Module authentication
  login:
    name: ${sls:stage}-login
    handler: src/authentication/login.handler
    role: ApiAccessRole
    events:
      - http:
          path: login
          method: post
          cors: true
          integration: lambda-proxy
    package:
      exclude:
        - "**"
      include:
        - src/authentication/login.py

resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-userpool

    CognitoUserPoolAuthorizer:
      Type: "AWS::ApiGateway::Authorizer"
      Properties:
        IdentitySource: "method.request.header.Authorization"
        Name: "CognitoUserPoolAuthorizer"
        RestApiId:
          Ref: "ApiGatewayRestApi"
        Type: "COGNITO_USER_POOLS"
        ProviderARNs:
          - arn:aws:cognito-idp:${self:custom.region}:${self:custom.account-id}:userpool/${self:custom.userpool-id}

    ApiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      DependsOn: CognitoUserPoolAuthorizer
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        Description: "Auto-deployed on #{AWS::AccountId}-#{AWS::StackName}-#{AWS::Region}"
      Metadata:
        Timestamp: "#{AWS::AccountId}-#{AWS::StackName}-#{AWS::Region}"

    ApiGatewayStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
        DeploymentId:
          Ref: ApiGatewayDeployment
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${self:provider.stage}

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-userpool-client
        UserPoolId:
          Ref: MyUserPool
        GenerateSecret: false
        RefreshTokenValidity: 60 # 60 day for refresh token
        AccessTokenValidity: 4 # 3 hour for access token
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH

    ApiAccessRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ApiAccessRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "ApiAccessPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                    - "cognito-idp:AdminInitiateAuth"
                  Resource:
                    - "*"
