version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::014183400304:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1BQGN88VZNW6"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-8X0JCouixr2o"
cloudformation_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-2HOSg14NKgU9"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1mqvdi7vxohx0"
image_repository = ""
region = "ap-southeast-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-imPRiY2VZe0e"
cloudformation_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-17ZLem1RtGbe"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-123obv6jq0bdf"
image_repository = ""
region = "ap-southeast-1"
