AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Patient functions stack."

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  LambdaAuthorizerFunctionArn:
    Type: String
  UserPoolId:
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Name: !Sub "${StageName}-${AppName}-private-access-api"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !Ref LambdaAuthorizerFunctionArn

  SendOTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: otp-sender
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DYNAMODB: !Sub "${StageName}-${AppName}-db"
          MAIL_1: "nguyengiantuananh@gmail.com"
          MAIL_2: "anhngthe151394@fpt.edu.vn"
          SENDER_MAIL: "nguyengiantuananh@gmail.com"
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /private-access/{id}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  SetNewPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: set-new-password
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DYNAMODB: !Sub "${StageName}-${AppName}-db"
          USER_POOL_ID: !Ref UserPoolId
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /private-access
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"
