AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Patient functions stack"

Parameters:
  Server:
    Type: String
  Database:
    Type: String
  Username:
    Type: String
  Password:
    Type: String
  ODBCLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String

Resources:
  GetAPatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: patient/
      Handler: get_a_patient.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref ODBCLayerArn
      Environment:
        Variables:
          SERVER: !Ref Server
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password

Outputs:
  GetAPatientFunctionArn:
    Description: "ARN of the GetAPatient function"
    Value: !GetAtt GetAPatientFunction.Arn
