AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Nested stack for all lambda functions"

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  DBHost:
    Type: String
    Description: "Database host address"
  Database:
    Type: String
    Description: "Database name"
  Username:
    Type: String
    Description: "Database username"
  Password:
    Type: String
    Description: "Database password"
    NoEcho: true
  PyMySQLLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String

Resources:
  PatientFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: patient/patient.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MedicalProcedureGroupFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: medical-procedure-group/medical-procedure-group.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MedicalProcedureFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: medical-procedure/medical-procedure.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  TreatmentCourseGroupFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: treatment-course/treatment-course.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  FacilityGroupFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: facility/facility.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  LaboFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: labo/labo.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MedicalSupplyFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: medical-supply/medical-supply.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MaterialFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: material/material.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  ImportMaterialFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: import-material/import-material.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MaterialWarehouseFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: material-warehouse/material-warehouse.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  ExaminationFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: examination/examination.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MaterialUsageFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: material-usage/material-usage.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  PaidMaterialUsageFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: paid-material-usage/paid-material-usage.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  MpTcFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: mp_tc/mp_tc.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password
        PyMySQLLayerArn: !Ref PyMySQLLayerArn