AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Patient functions stack."

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  DBHost:
    Type: String
  Database:
    Type: String
  Username:
    Type: String
  Password:
    Type: String
  PyMySQLLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String
  LambdaAuthorizerFunctionArn:
    Type: String
  BucketImageName:
    Type: String
  Region:
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Name: !Sub "${StageName}-${AppName}-x-ray-image-api"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !Ref LambdaAuthorizerFunctionArn

  CreateXRayImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
          BUCKET_IMAGE_NAME: !Ref BucketImageName
          REGION: !Ref Region
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /x-ray-image
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  DeleteXRayImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /x-ray-image/{patient_id}/{url}
            Method: delete
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetByPatientIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-by-patient-id
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /x-ray-image/patient/{id}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"
