AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Patient functions stack."

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  DBHost:
    Type: String
  Database:
    Type: String
  Username:
    Type: String
  Password:
    Type: String
  PyMySQLLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Name: !Sub "${StageName}-${AppName}-import-material-api"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn

  CreateAImportMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  UpdateAImportMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material/{id}
            Method: put
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  DeleteAImportMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material/{id}
            Method: delete
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetImportMaterialByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-by-id
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material/{id}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetImportMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material/page/{paging}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetImportMaterialByDateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-by-date-to-date
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /import-material/date/{start-date}/{end-date}/{paging}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"
