AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Dental-Clinic-Managerment-System

Globals:
  Function:
    Timeout: 5
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Description: Stage name
    Default: dev
  DBServer:
    Type: String
    Description: "Database server name"
    Default: "nguyen-tran-clinic-db.c4a0pr3rutpd.ap-southeast-1.rds.amazonaws.com"
  Database:
    Type: String
    Description: "Database name"
    Default: "nguyen-tran-clinic"
  DBUsername:
    Type: String
    Description: "Database username"
    Default: "admin"
  DBPassword:
    Type: String
    Description: "Database password"
    Default: "sA2PH6km3AmSj8wCHlKl"
    NoEcho: true
  ODBCLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String
    Default: "arn:aws:lambda:ap-southeast-1:014183400304:layer:ODBCLayer:2"

Resources:
  InfrastructureStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/infrastructure.yaml
      Parameters:
        TableName: !Sub "${StageName}-nguyen-tran-clinic"
        StageName: !Sub ${StageName}
        AppName: "dmcs"

  LambdaFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda-functions/lambda-functions.yaml
      Parameters:
        Server: !Ref DBServer
        Database: !Ref Database
        Username: !Ref DBUsername
        Password: !Ref DBPassword
        ODBCLayerArn: !Ref ODBCLayerArn
