AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Dental-Clinic-Managerment-System

Globals:
  Function:
    Timeout: 5
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Description: Stage name
    Default: dev
  DBServer:
    Type: String
    Description: "Database server name"
    Default: "nguyen-tran-clinic-db.c4a0pr3rutpd.ap-southeast-1.rds.amazonaws.com"
  Database:
    Type: String
    Description: "Database name"
    Default: "nguyen-tran-clinic"
  DBUsername:
    Type: String
    Description: "Database username"
    Default: "admin"
  DBPassword:
    Type: String
    Description: "Database password"
    Default: "sA2PH6km3AmSj8wCHlKl"
    NoEcho: true

Resources:
  InfrastructureStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/infrastructure.yaml
      Parameters:
        TableName: !Sub "${StageName}-nguyen-tran-clinic"
        StageName: !Sub ${StageName}
        AppName: "dmcs"

  ODBCLayer:
    Type: "AWS::Include"
    Properties:
      Location: ./lambda-layer/lambda-layer.yaml

  LambdaFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda-functions/lambda-functions.yaml
      Parameters:
        Server: !Ref Server
        Database: !Ref Database
        Username: !Ref Username
        Password: !Ref Password

Outputs:
  ODBCLayerArn:
    Description: "ODBC Layer ARN"
    Value:
      Fn::GetAtt:
        - ODBCLayer
        - Arn
    Export:
      Name: ODBCLayerArn
