AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Dental-Clinic-Managerment-System.

Globals:
  Function:
    Timeout: 5
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  StageName:
    Type: String
    Description: Stage name
    Default: dev
  DBHost:
    Type: String
    Description: "Database host address"
    Default: "nguyen-tran-clinic-db.c4a0pr3rutpd.ap-southeast-1.rds.amazonaws.com"
  Database:
    Type: String
    Description: "Database name"
    Default: "nguyen_tran_clinic"
  DBUsername:
    Type: String
    Description: "Database username"
    Default: "admin"
  DBPassword:
    Type: String
    Description: "Database password"
    Default: "COMK9szvsdq8EyJEC0Hq"
    NoEcho: true
  PyMySQLLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String
    Default: "arn:aws:lambda:ap-southeast-1:014183400304:layer:PyMySQL:1"
  AppName:
    Type: String
    Default: "dcms"

Resources:
  InfrastructureStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/infrastructure.yaml
      Parameters:
        TableName: !Sub "${StageName}-nguyen-tran-clinic"
        StageName: !Sub ${StageName}
        AppName: !Sub ${AppName}

  LambdaFunctions:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfrastructureStack
    Properties:
      TemplateURL: ./lambda-functions/lambda-functions.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Sub ${AppName}
        UserPoolArn: !GetAtt InfrastructureStack.Outputs.CognitoUserPoolArn
        UserPoolId: !GetAtt InfrastructureStack.Outputs.CognitoUserPoolId
        DBHost: !Ref DBHost
        Database: !Ref Database
        Username: !Ref DBUsername
        Password: !Ref DBPassword
        PyMySQLLayerArn: !Ref PyMySQLLayerArn

  IntegratedResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunctions
    Properties:
      TemplateURL: ./integrated-resource/integrated-resource.yaml
      Parameters:
        StageName: !Ref StageName
        UserPoolArn: !GetAtt InfrastructureStack.Outputs.CognitoUserPoolArn
        TableName: !Sub "${StageName}-${AppName}-db"
        AppName: !Sub ${AppName}
        LambdaAuthorizerFunctionArn: !GetAtt LambdaFunctions.Outputs.LambdaAuthorizerFunctionArn
