AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Patient functions stack."

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  DBHost:
    Type: String
  Database:
    Type: String
  Username:
    Type: String
  Password:
    Type: String
  PyMySQLLayerArn:
    Description: ARN of the Lambda layer to associate with our function
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Name: !Sub "${StageName}-${AppName}-material-usage-api"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn

  AddListMaterialUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-list
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  AddProcedureMaterialUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-procedure-usage
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage/procedure
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetByTreatmentCourseIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-by-treatment-course-id
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage/treatment-course/{id}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  GetMaterialUsageByDateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-by-date-to-date
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage/report/{start-date}/{end-date}
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  UpdateMaterialUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage/{id}
            Method: put
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"

  DeleteMaterialUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PyMySQLLayerArn
      Environment:
        Variables:
          HOST: !Ref DBHost
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Events:
        CreateActivities:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /material-usage/{id}
            Method: delete
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "rds:*"
              Resource: "*"
