AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Nested stack for all intergrated to resource dynamodb"

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  TableName:
    Type: String
  UserPoolArn:
    Type: String

Resources:
  Api:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${StageName}-${AppName}-integrated-resource-api"

  InteCognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: InteCognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref Api
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Ref UserPoolArn

  WaitingRoomStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./waiting-room.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
