AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Nested stack for all intergrated to resource dynamodb"

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  TableName:
    Type: String
  UserPoolArn:
    Type: String
  LambdaAuthorizerFunctionArn:
    Type: String
    
Resources:
  Api:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${StageName}-${AppName}-integrated-resource-api"

  InteCognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: InteCognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref Api
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Ref UserPoolArn

  LambdaAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: "LambdaAuthorizer"
      RestApiId: !Ref Api
      Type: TOKEN
      IdentitySource: "method.request.header.Authorization"
      AuthorizerUri: !Sub arn:aws:apigateway:ap-southeast-1:lambda:path/2015-03-31/functions/${LambdaAuthorizerFunctionArn}/invocations
      AuthorizerResultTtlInSeconds: 300

  APIGatewayIntegreatedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: APIGatewayDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource: "*"

  WaitingRoomStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./waiting-room.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        LambdaAuthorizer: !Ref LambdaAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
        APIGatewayIntegreatedRoleArn: !GetAtt APIGatewayIntegreatedRole.Arn

  AppointmentStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./appointment.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
        APIGatewayIntegreatedRoleArn: !GetAtt APIGatewayIntegreatedRole.Arn

  TimekeepingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./timekeeping.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
        APIGatewayIntegreatedRoleArn: !GetAtt APIGatewayIntegreatedRole.Arn

  MessageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./message.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
        APIGatewayIntegreatedRoleArn: !GetAtt APIGatewayIntegreatedRole.Arn

  ExpensesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./expenses.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        UserPoolArn: !Ref UserPoolArn
        TableName: !Ref TableName
        Api: !Ref Api
        InteCognitoAuthorizer: !Ref InteCognitoAuthorizer
        ApiRootResourceId: !GetAtt Api.RootResourceId
        APIGatewayIntegreatedRoleArn: !GetAtt APIGatewayIntegreatedRole.Arn