AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Integrated to resource dynamodb."

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  UserPoolArn:
    Type: String
  TableName:
    Type: String

Resources:
  APIGatewayIntegreatedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: APIGatewayDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource: "*"

  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: !Ref StageName
      Name: !Sub "${StageName}-${AppName}-api"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref AppName
        paths:
          /waiting-room:
            post:
              x-amazon-apigateway-integration:
                type: "aws"
                credentials: !GetAtt APIGatewayIntegreatedRole.Arn
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem"
                passthroughBehavior: "WHEN_NO_TEMPLATES"
                requestTemplates:
                  application/json:
                    "Fn::Sub": '{"TableName":"${TableName}","Item":{"type":{"S":"$input.path(''$.type'')"},"epoch":{"S":"$input.path(''$.epoch'')"},"info":{"S":"$input.path(''$.info'')"}}}'
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: "{}"
              responses:
                "200":
                  description: "200 response"
              security:
                - MyCognitoAuthorizer: []
        securityDefinitions:
          MyCognitoAuthorizer:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authorizer:
              type: "cognito_user_pools"
              providerARNs:
                - !Ref UserPoolArn
